calculator:
	g++ -std=c++17 -o calculator calculator.cpp TokenStream.cpp Interpreter.cpp

clean:
	rm -f *.o
	g++ -std=c++17 -o calculator calculator.cpp TokenStream.cpp Interpreter.cpp

cleanest:
	rm -f *.o
	rm -f *.o calculator
	g++ -std=c++17 -o calculator calculator.cpp TokenStream.cpp Interpreter.cpp
	
